<?php
/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-05-09 at 17:06:15.
 */
class PredictableQueueTest extends TestCase
{
    /**
     * @var PredictableQueue
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    public function setUp()
    {
        $this->object = new PredictableQueue;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers PredictableQueue::scan
     * @todo   Implement testScan().
     */
    public function testScan()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PredictableQueue::processPredictable
     * @todo   Implement testProcessPredictable().
     */
    public function testProcessPredictable()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PredictableQueue::processTransaction
     * @todo   Implement testProcessTransaction().
     */
    public function testProcessTransaction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
