language: php
php:
  - 5.5
  - 5.4
install:
  - composer install
  - php artisan firefly:install --env=travis

before_install:
  - mysql -e 'create database firefly;'

src_dir: .

after_script:
  - php vendor/bin/coveralls