<?php
/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-05-09 at 17:01:20.
 */
class AuthenticatedCacheFileStoreTest extends TestCase
{
    /**
     * @var AuthenticatedCacheFileStore
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    public function setUp()
    {
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers AuthenticatedCacheFileStore::get
     * @todo   Implement testGet().
     */
    public function testGet()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AuthenticatedCacheFileStore::put
     * @todo   Implement testPut().
     */
    public function testPut()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AuthenticatedCacheFileStore::increment
     * @todo   Implement testIncrement().
     */
    public function testIncrement()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AuthenticatedCacheFileStore::decrement
     * @todo   Implement testDecrement().
     */
    public function testDecrement()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AuthenticatedCacheFileStore::forever
     * @todo   Implement testForever().
     */
    public function testForever()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AuthenticatedCacheFileStore::forget
     * @todo   Implement testForget().
     */
    public function testForget()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AuthenticatedCacheFileStore::flush
     * @todo   Implement testFlush().
     */
    public function testFlush()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AuthenticatedCacheFileStore::userFlush
     * @todo   Implement testUserFlush().
     */
    public function testUserFlush()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AuthenticatedCacheFileStore::getPrefix
     * @todo   Implement testGetPrefix().
     */
    public function testGetPrefix()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
