<?php
/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-05-09 at 17:01:28.
 */
class UserArrayStoreTest extends TestCase
{
    /**
     * @var UserArrayStore
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    public function setUp()
    {
        $this->object = new UserArrayStore;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers UserArrayStore::userFlush
     * @todo   Implement testUserFlush().
     */
    public function testUserFlush()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
