<?php
/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-05-09 at 16:58:52.
 */
class ProfileControllerTest extends TestCase
{
    /**
     * @var ProfileController
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    public function setUp()
    {
        $this->object = new ProfileController;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers ProfileController::index
     * @todo   Implement testIndex().
     */
    public function testIndex()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ProfileController::changePassword
     * @todo   Implement testChangePassword().
     */
    public function testChangePassword()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ProfileController::postChangePassword
     * @todo   Implement testPostChangePassword().
     */
    public function testPostChangePassword()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ProfileController::changeUsername
     * @todo   Implement testChangeUsername().
     */
    public function testChangeUsername()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ProfileController::postChangeUsername
     * @todo   Implement testPostChangeUsername().
     */
    public function testPostChangeUsername()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
