<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-05-09 at 17:06:51.
 */
class SearchControllerTest extends TestCase
{

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    public function setUp()
    {
        parent::setUp();
        $user = User::where('username', 'admin')->first();
        $this->be($user);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers SearchController::search
     * @todo   Implement testSearch().
     */
    public function testSearch()
    {
        // search for a term, make sure the results bla bla match what we expected to find?
        $query = ['query' => 'Checking'];

        $response = $this->action('GET', 'SearchController@search', $query);
        $view = $response->original;
        $this->assertResponseOk();
        $this->assertEquals('Searching for "' . $query['query'] . '"', $view['title']);
        // find one account:
        $this->assertEquals(1, $view['result']['count']['accounts']);
    }
}
