<?php
/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-05-09 at 17:03:33.
 */
class AccountTest extends TestCase
{
    /**
     * @var Account
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    public function setUp()
    {
        $this->object = new Account;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Account::user
     * @todo   Implement testUser().
     */
    public function testUser()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Account::transfersto
     * @todo   Implement testTransfersto().
     */
    public function testTransfersto()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Account::predictables
     * @todo   Implement testPredictables().
     */
    public function testPredictables()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Account::transfersfrom
     * @todo   Implement testTransfersfrom().
     */
    public function testTransfersfrom()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Account::balanceOnDate
     * @todo   Implement testBalanceOnDate().
     */
    public function testBalanceOnDate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Account::balancemodifiers
     * @todo   Implement testBalancemodifiers().
     */
    public function testBalancemodifiers()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Account::predictOnDate
     * @todo   Implement testPredictOnDate().
     */
    public function testPredictOnDate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Account::predictionInformation
     * @todo   Implement testPredictionInformation().
     */
    public function testPredictionInformation()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Account::transactions
     * @todo   Implement testTransactions().
     */
    public function testTransactions()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Account::getDates
     * @todo   Implement testGetDates().
     */
    public function testGetDates()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Account::scopeNotInactive
     * @todo   Implement testScopeNotInactive().
     */
    public function testScopeNotInactive()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Account::scopeShared
     * @todo   Implement testScopeShared().
     */
    public function testScopeShared()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Account::scopeNotShared
     * @todo   Implement testScopeNotShared().
     */
    public function testScopeNotShared()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
