<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-04-07 at 16:42:07.
 */
class BalancemodifierTest extends TestCase
{
    /**
     * @var Balancemodifier
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    public function setUp()
    {
        parent::setUp();
        $this->object = new Balancemodifier;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Balancemodifier::account
     * @todo   Implement testAccount().
     */
    public function testAccount()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Balancemodifier::getDates
     * @todo   Implement testGetDates().
     */
    public function testGetDates()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Balancemodifier::scopeOnDay
     * @todo   Implement testScopeOnDay().
     */
    public function testScopeOnDay()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Balancemodifier::scopeBeforeDay
     * @todo   Implement testScopeBeforeDay().
     */
    public function testScopeBeforeDay()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
