<?php
/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-05-09 at 17:04:50.
 */
class ComponentEnabledModelTest extends TestCase
{
    /**
     * @var ComponentEnabledModel
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    public function setUp()
    {
        $this->object = new ComponentEnabledModel;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers ComponentEnabledModel::hasComponentOfType
     * @todo   Implement testHasComponentOfType().
     */
    public function testHasComponentOfType()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ComponentEnabledModel::getComponentOfType
     * @todo   Implement testGetComponentOfType().
     */
    public function testGetComponentOfType()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ComponentEnabledModel::saveComponentsFromInput
     * @todo   Implement testSaveComponentsFromInput().
     */
    public function testSaveComponentsFromInput()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
