<?php
/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-05-09 at 17:04:46.
 */
class ComponentTest extends TestCase
{
    /**
     * @var Component
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    public function setUp()
    {
        $this->object = new Component;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Component::findOrCreate
     * @todo   Implement testFindOrCreate().
     */
    public function testFindOrCreate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Component::parentComponent
     * @todo   Implement testParentComponent().
     */
    public function testParentComponent()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Component::childrenComponents
     * @todo   Implement testChildrenComponents().
     */
    public function testChildrenComponents()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Component::type
     * @todo   Implement testType().
     */
    public function testType()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Component::getTypeAttribute
     * @todo   Implement testGetTypeAttribute().
     */
    public function testGetTypeAttribute()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Component::limits
     * @todo   Implement testLimits().
     */
    public function testLimits()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Component::transactions
     * @todo   Implement testTransactions().
     */
    public function testTransactions()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Component::transfers
     * @todo   Implement testTransfers().
     */
    public function testTransfers()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Component::predictables
     * @todo   Implement testPredictables().
     */
    public function testPredictables()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Component::user
     * @todo   Implement testUser().
     */
    public function testUser()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Component::getDates
     * @todo   Implement testGetDates().
     */
    public function testGetDates()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Component::scopeReporting
     * @todo   Implement testScopeReporting().
     */
    public function testScopeReporting()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Component::getDestinationPath
     * @todo   Implement testGetDestinationPath().
     */
    public function testGetDestinationPath()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Component::hasIcon
     * @todo   Implement testHasIcon().
     */
    public function testHasIcon()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Component::iconTag
     * @todo   Implement testIconTag().
     */
    public function testIconTag()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Component::iconFileLocation
     * @todo   Implement testIconFileLocation().
     */
    public function testIconFileLocation()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
