<?php
/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-05-09 at 17:05:20.
 */
class PredictableTest extends TestCase
{
    /**
     * @var Predictable
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    public function setUp()
    {
        $this->object = new Predictable;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Predictable::user
     * @todo   Implement testUser().
     */
    public function testUser()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Predictable::account
     * @todo   Implement testAccount().
     */
    public function testAccount()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Predictable::scopeActive
     * @todo   Implement testScopeActive().
     */
    public function testScopeActive()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Predictable::components
     * @todo   Implement testComponents().
     */
    public function testComponents()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Predictable::transactions
     * @todo   Implement testTransactions().
     */
    public function testTransactions()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Predictable::getDates
     * @todo   Implement testGetDates().
     */
    public function testGetDates()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Predictable::minimumAmount
     * @todo   Implement testMinimumAmount().
     */
    public function testMinimumAmount()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Predictable::maximumAmount
     * @todo   Implement testMaximumAmount().
     */
    public function testMaximumAmount()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Predictable::dayOfMonth
     * @todo   Implement testDayOfMonth().
     */
    public function testDayOfMonth()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
