<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-04-07 at 16:49:18.
 */
class TransactionTest extends TestCase
{
    /**
     * @var Transaction
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    public function setUp()
    {
        parent::setUp();
        $this->object = new Transaction;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Transaction::getBeneficiaryAttribute
     * @todo   Implement testGetBeneficiaryAttribute().
     */
    public function testGetBeneficiaryAttribute()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Transaction::getCategoryAttribute
     * @todo   Implement testGetCategoryAttribute().
     */
    public function testGetCategoryAttribute()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Transaction::getBudgetAttribute
     * @todo   Implement testGetBudgetAttribute().
     */
    public function testGetBudgetAttribute()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Transaction::account
     * @todo   Implement testAccount().
     */
    public function testAccount()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Transaction::attachComponent
     * @todo   Implement testAttachComponent().
     */
    public function testAttachComponent()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Transaction::components
     * @todo   Implement testComponents().
     */
    public function testComponents()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Transaction::scopeInMonth
     * @todo   Implement testScopeInMonth().
     */
    public function testScopeInMonth()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Transaction::scopeInYear
     * @todo   Implement testScopeInYear().
     */
    public function testScopeInYear()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Transaction::scopeOnDay
     * @todo   Implement testScopeOnDay().
     */
    public function testScopeOnDay()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Transaction::scopeBetweenDates
     * @todo   Implement testScopeBetweenDates().
     */
    public function testScopeBetweenDates()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Transaction::scopeExpenses
     * @todo   Implement testScopeExpenses().
     */
    public function testScopeExpenses()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Transaction::scopeAfterDate
     * @todo   Implement testScopeAfterDate().
     */
    public function testScopeAfterDate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Transaction::scopeBeforeDate
     * @todo   Implement testScopeBeforeDate().
     */
    public function testScopeBeforeDate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Transaction::scopeIncomes
     * @todo   Implement testScopeIncomes().
     */
    public function testScopeIncomes()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Transaction::user
     * @todo   Implement testUser().
     */
    public function testUser()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Transaction::predictable
     * @todo   Implement testPredictable().
     */
    public function testPredictable()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Transaction::getDescriptionAttribute
     * @todo   Implement testGetDescriptionAttribute().
     */
    public function testGetDescriptionAttribute()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Transaction::setDescriptionAttribute
     * @todo   Implement testSetDescriptionAttribute().
     */
    public function testSetDescriptionAttribute()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Transaction::getDates
     * @todo   Implement testGetDates().
     */
    public function testGetDates()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
