<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-04-07 at 16:49:27.
 */
class TransferTest extends TestCase
{
    /**
     * @var Transfer
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    public function setUp()
    {
        parent::setUp();
        $this->object = new Transfer;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Transfer::accountfrom
     * @todo   Implement testAccountfrom().
     */
    public function testAccountfrom()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Transfer::accountto
     * @todo   Implement testAccountto().
     */
    public function testAccountto()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Transfer::components
     * @todo   Implement testComponents().
     */
    public function testComponents()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Transfer::getBeneficiaryAttribute
     * @todo   Implement testGetBeneficiaryAttribute().
     */
    public function testGetBeneficiaryAttribute()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Transfer::getCategoryAttribute
     * @todo   Implement testGetCategoryAttribute().
     */
    public function testGetCategoryAttribute()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Transfer::getBudgetAttribute
     * @todo   Implement testGetBudgetAttribute().
     */
    public function testGetBudgetAttribute()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Transfer::user
     * @todo   Implement testUser().
     */
    public function testUser()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Transfer::scopeInMonth
     * @todo   Implement testScopeInMonth().
     */
    public function testScopeInMonth()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Transfer::scopeInYear
     * @todo   Implement testScopeInYear().
     */
    public function testScopeInYear()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Transfer::getDescriptionAttribute
     * @todo   Implement testGetDescriptionAttribute().
     */
    public function testGetDescriptionAttribute()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Transfer::attachComponent
     * @todo   Implement testAttachComponent().
     */
    public function testAttachComponent()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Transfer::setDescriptionAttribute
     * @todo   Implement testSetDescriptionAttribute().
     */
    public function testSetDescriptionAttribute()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Transfer::getDates
     * @todo   Implement testGetDates().
     */
    public function testGetDates()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Transfer::scopeBeforeDate
     * @todo   Implement testScopeBeforeDate().
     */
    public function testScopeBeforeDate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
