<?php
/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-05-09 at 17:05:37.
 */
class TypeTest extends TestCase
{
    /**
     * @var Type
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    public function setUp()
    {
        $this->object = new Type;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Type::components
     * @todo   Implement testComponents().
     */
    public function testComponents()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Type::getIcon
     * @todo   Implement testGetIcon().
     */
    public function testGetIcon()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Type::allTypes
     * @todo   Implement testAllTypes().
     */
    public function testAllTypes()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
