<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-04-07 at 16:52:52.
 */
class AccountTriggerTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var AccountTrigger
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new AccountTrigger;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers AccountTrigger::editAccount
     * @todo   Implement testEditAccount().
     */
    public function testEditAccount()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AccountTrigger::createAccount
     * @todo   Implement testCreateAccount().
     */
    public function testCreateAccount()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AccountTrigger::validateAccountName
     * @todo   Implement testValidateAccountName().
     */
    public function testValidateAccountName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AccountTrigger::subscribe
     * @todo   Implement testSubscribe().
     */
    public function testSubscribe()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
