<?php
/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-05-09 at 17:00:12.
 */
class ComponentTriggerTest extends TestCase
{
    /**
     * @var ComponentTrigger
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    public function setUp()
    {
        $this->object = new ComponentTrigger;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers ComponentTrigger::validateComponent
     * @todo   Implement testValidateComponent().
     */
    public function testValidateComponent()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ComponentTrigger::subscribe
     * @todo   Implement testSubscribe().
     */
    public function testSubscribe()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
