<?php
/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-05-09 at 17:00:18.
 */
class LimitTriggerTest extends TestCase
{
    /**
     * @var LimitTrigger
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    public function setUp()
    {
        $this->object = new LimitTrigger;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers LimitTrigger::createLimit
     * @todo   Implement testCreateLimit().
     */
    public function testCreateLimit()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers LimitTrigger::subscribe
     * @todo   Implement testSubscribe().
     */
    public function testSubscribe()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
