<?php
/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-05-09 at 17:00:36.
 */
class PredictableTriggerTest extends TestCase
{
    /**
     * @var PredictableTrigger
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    public function setUp()
    {
        $this->object = new PredictableTrigger;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers PredictableTrigger::validatePredictable
     * @todo   Implement testValidatePredictable().
     */
    public function testValidatePredictable()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PredictableTrigger::jobPredictable
     * @todo   Implement testJobPredictable().
     */
    public function testJobPredictable()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PredictableTrigger::subscribe
     * @todo   Implement testSubscribe().
     */
    public function testSubscribe()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
