<?php
/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-05-09 at 17:00:55.
 */
class TransferTriggerTest extends TestCase
{
    /**
     * @var TransferTrigger
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    public function setUp()
    {
        $this->object = new TransferTrigger;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers TransferTrigger::createTransfer
     * @todo   Implement testCreateTransfer().
     */
    public function testCreateTransfer()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TransferTrigger::editTransfer
     * @todo   Implement testEditTransfer().
     */
    public function testEditTransfer()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TransferTrigger::deleteTransfer
     * @todo   Implement testDeleteTransfer().
     */
    public function testDeleteTransfer()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TransferTrigger::subscribe
     * @todo   Implement testSubscribe().
     */
    public function testSubscribe()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
