<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-04-07 at 16:53:14.
 */
class TransferTriggerTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var TransferTrigger
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new TransferTrigger;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers TransferTrigger::createTransfer
     * @todo   Implement testCreateTransfer().
     */
    public function testCreateTransfer()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TransferTrigger::editTransfer
     * @todo   Implement testEditTransfer().
     */
    public function testEditTransfer()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TransferTrigger::deleteTransfer
     * @todo   Implement testDeleteTransfer().
     */
    public function testDeleteTransfer()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers TransferTrigger::subscribe
     * @todo   Implement testSubscribe().
     */
    public function testSubscribe()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
