<?php

use Carbon\Carbon as Carbon;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-04-07 at 04:27:58.
 */
class AccountHelperTest extends TestCase
{
    /**
     * @var AccountHelper
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    public function setUp()
    {
        parent::setUp();
        $this->object = new AccountHelper;
        $user = User::where('username', 'test')->first();
        $this->be($user);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers AccountHelper::accountsAsSelectList
     */
    public function testAccountsAsSelectList()
    {
        $count = Auth::user()->accounts()->where('hidden', 0)->count();
        $list = AccountHelper::accountsAsSelectList();
        $this->assertCount($count, $list);

    }

    /**
     * @covers AccountHelper::months
     * @todo   Implement testMonths().
     */
    public function testMonths()
    {
        //We use the Toolkit as well. Is that bad?
        $end = new Carbon;
        $end->firstOfMonth();
        $start = Toolkit::getEarliestEvent();
        // diff includes current month.
        $diff = $end->diffInMonths($start) + 1;

        // account:
        $account = Auth::user()->accounts()->first();

        // get data:
        $list = AccountHelper::months($account);
        $this->assertCount($diff,$list);


    }

    /**
     * @covers AccountHelper::mutations
     * @todo   Implement testMutations().
     */
    public function testMutations()
    {



        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AccountHelper::getPredictionStart
     * @todo   Implement testGetPredictionStart().
     */
    public function testGetPredictionStart()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AccountHelper::getMarkedTransactions
     * @todo   Implement testGetMarkedTransactions().
     */
    public function testGetMarkedTransactions()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AccountHelper::emptyPrefilledAray
     * @todo   Implement testEmptyPrefilledAray().
     */
    public function testEmptyPrefilledAray()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AccountHelper::prefilledFromOldInput
     * @todo   Implement testPrefilledFromOldInput().
     */
    public function testPrefilledFromOldInput()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AccountHelper::prefilledFromAccount
     * @todo   Implement testPrefilledFromAccount().
     */
    public function testPrefilledFromAccount()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
