<?php
/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-05-09 at 17:02:03.
 */
class AccountHelperTest extends TestCase
{
    /**
     * @var AccountHelper
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    public function setUp()
    {
        $this->object = new AccountHelper;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers AccountHelper::accountsAsSelectList
     * @todo   Implement testAccountsAsSelectList().
     */
    public function testAccountsAsSelectList()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AccountHelper::months
     * @todo   Implement testMonths().
     */
    public function testMonths()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AccountHelper::mutations
     * @todo   Implement testMutations().
     */
    public function testMutations()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AccountHelper::getPredictionStart
     * @todo   Implement testGetPredictionStart().
     */
    public function testGetPredictionStart()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AccountHelper::getMarkedTransactions
     * @todo   Implement testGetMarkedTransactions().
     */
    public function testGetMarkedTransactions()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AccountHelper::emptyPrefilledAray
     * @todo   Implement testEmptyPrefilledAray().
     */
    public function testEmptyPrefilledAray()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AccountHelper::prefilledFromOldInput
     * @todo   Implement testPrefilledFromOldInput().
     */
    public function testPrefilledFromOldInput()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers AccountHelper::prefilledFromAccount
     * @todo   Implement testPrefilledFromAccount().
     */
    public function testPrefilledFromAccount()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
