<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-04-07 at 04:29:58.
 */
class ComponentHelperTest extends TestCase
{
    /**
     * @var ComponentHelper
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    public function setUp()
    {
        $this->object = new ComponentHelper;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers ComponentHelper::months
     * @todo   Implement testMonths().
     */
    public function testMonths()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ComponentHelper::mutations
     * @todo   Implement testMutations().
     */
    public function testMutations()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ComponentHelper::generateTransactionListByMonth
     * @todo   Implement testGenerateTransactionListByMonth().
     */
    public function testGenerateTransactionListByMonth()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ComponentHelper::transactionsWithoutComponent
     * @todo   Implement testTransactionsWithoutComponent().
     */
    public function testTransactionsWithoutComponent()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ComponentHelper::getParentList
     * @todo   Implement testGetParentList().
     */
    public function testGetParentList()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ComponentHelper::emptyPrefilledAray
     * @todo   Implement testEmptyPrefilledAray().
     */
    public function testEmptyPrefilledAray()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ComponentHelper::prefilledFromOldInput
     * @todo   Implement testPrefilledFromOldInput().
     */
    public function testPrefilledFromOldInput()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ComponentHelper::prefilledFromComponent
     * @todo   Implement testPrefilledFromComponent().
     */
    public function testPrefilledFromComponent()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ComponentHelper::saveComponentFromText
     * @todo   Implement testSaveComponentFromText().
     */
    public function testSaveComponentFromText()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
