<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-04-07 at 16:38:33.
 */
class PiggybankHelperTest extends TestCase
{
    /**
     * @var PiggybankHelper
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    public function setUp()
    {
        parent::setUp();
        $this->object = new PiggybankHelper;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers PiggybankHelper::emptyPrefilledAray
     * @todo   Implement testEmptyPrefilledAray().
     */
    public function testEmptyPrefilledAray()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PiggybankHelper::prefilledFromOldInput
     * @todo   Implement testPrefilledFromOldInput().
     */
    public function testPrefilledFromOldInput()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PiggybankHelper::prefilledFromPiggybank
     * @todo   Implement testPrefilledFromPiggybank().
     */
    public function testPrefilledFromPiggybank()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
