<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-04-07 at 04:31:31.
 */
class PredictableHelperTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var PredictableHelper
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new PredictableHelper;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers PredictableHelper::componentList
     * @todo   Implement testComponentList().
     */
    public function testComponentList()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PredictableHelper::emptyPrefilledAray
     * @todo   Implement testEmptyPrefilledAray().
     */
    public function testEmptyPrefilledAray()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PredictableHelper::prefilledFromOldInput
     * @todo   Implement testPrefilledFromOldInput().
     */
    public function testPrefilledFromOldInput()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PredictableHelper::prefilledFromTransaction
     * @todo   Implement testPrefilledFromTransaction().
     */
    public function testPrefilledFromTransaction()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PredictableHelper::prefilledFromPredictable
     * @todo   Implement testPrefilledFromPredictable().
     */
    public function testPrefilledFromPredictable()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
