<?php
/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-05-09 at 17:02:34.
 */
class ReportHelperTest extends TestCase
{
    /**
     * @var ReportHelper
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    public function setUp()
    {
        $this->object = new ReportHelper;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers ReportHelper::summaryCompared
     * @todo   Implement testSummaryCompared().
     */
    public function testSummaryCompared()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ReportHelper::monthsCompared
     * @todo   Implement testMonthsCompared().
     */
    public function testMonthsCompared()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ReportHelper::summary
     * @todo   Implement testSummary().
     */
    public function testSummary()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ReportHelper::biggestExpenses
     * @todo   Implement testBiggestExpenses().
     */
    public function testBiggestExpenses()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ReportHelper::predicted
     * @todo   Implement testPredicted().
     */
    public function testPredicted()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ReportHelper::months
     * @todo   Implement testMonths().
     */
    public function testMonths()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ReportHelper::incomes
     * @todo   Implement testIncomes().
     */
    public function testIncomes()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ReportHelper::expensesGrouped
     * @todo   Implement testExpensesGrouped().
     */
    public function testExpensesGrouped()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ReportHelper::sortExpenses
     * @todo   Implement testSortExpenses().
     */
    public function testSortExpenses()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ReportHelper::sharedAccountsByMonth
     * @todo   Implement testSharedAccountsByMonth().
     */
    public function testSharedAccountsByMonth()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers ReportHelper::sharedAccounts
     * @todo   Implement testSharedAccounts().
     */
    public function testSharedAccounts()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
