<?php
/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-05-09 at 17:02:42.
 */
class SearchHelperTest extends TestCase
{
    /**
     * @var SearchHelper
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    public function setUp()
    {
        $this->object = new SearchHelper;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers SearchHelper::parseQuery
     * @todo   Implement testParseQuery().
     */
    public function testParseQuery()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SearchHelper::searchTransactions
     * @todo   Implement testSearchTransactions().
     */
    public function testSearchTransactions()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SearchHelper::searchTransfers
     * @todo   Implement testSearchTransfers().
     */
    public function testSearchTransfers()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SearchHelper::searchAccounts
     * @todo   Implement testSearchAccounts().
     */
    public function testSearchAccounts()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SearchHelper::searchBeneficiaries
     * @todo   Implement testSearchBeneficiaries().
     */
    public function testSearchBeneficiaries()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SearchHelper::searchCategories
     * @todo   Implement testSearchCategories().
     */
    public function testSearchCategories()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SearchHelper::searchBudgets
     * @todo   Implement testSearchBudgets().
     */
    public function testSearchBudgets()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
