<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-04-07 at 04:31:45.
 */
class ToolkitTest extends TestCase
{
    /**
     * @var Toolkit
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    public function setUp()
    {
        $this->object = new Toolkit;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Toolkit::parseDate
     * @todo   Implement testParseDate().
     */
    public function testParseDate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Toolkit::getFrontpageAccount
     * @todo   Implement testGetFrontpageAccount().
     */
    public function testGetFrontpageAccount()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Toolkit::getPredictionStart
     * @todo   Implement testGetPredictionStart().
     */
    public function testGetPredictionStart()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Toolkit::getEarliestEvent
     * @todo   Implement testGetEarliestEvent().
     */
    public function testGetEarliestEvent()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
